pythonProject/pythonProject/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy
from first_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/', views.show_info),
    path('showWorker/<int:id_user>/', views.show_worker, name='show_worker'),
    path('showWorker/<int:id_user>/addsalary/', views.create_payout, name='create_payout'),
    path('showWorker/<int:id_user>/<str:number_pay>/<deletesalary/', views.delete_payout, name='delete_payout'),
    path('addSalary/', views.create_payout),
    path('', views.show_index, name='home'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('home')), name='logout'),
    path('bossView/<int:id>/', views.show_department, name='show_department'),

    # ajax url
    path('ajax/validate_username', views.validate_username, name='validate_username'),
    path('ajax/validate_email', views.validate_email, name='validate_email'),
    path('ajax/check_numberPay', views.check_numberPay, name='check_numberPay')
]

pythonProject/first_app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.datetime_safe import date
from first_app.models import Salary
from bootstrap_datepicker_plus.widgets import DatePickerInput

''' class SalaryForms(forms.ModelForm):
    class Meta:
        model = Salary
        fields = ('number', 'payout', 'date_salary')'''


class SalaryForms(forms.Form):
    number = forms.CharField(help_text="Введите номер выплаты:")
    payout = forms.CharField(help_text="Внесите сумму выплаты:")
    date_salary = forms.DateField(help_text="Выберите дату зачисления выплаты:", widget=DatePickerInput())

    def clean_date_salary(self):
        date_local = self.cleaned_data['date_salary']
        print(date.today().day - date_local.day)
        payout = self.cleaned_data['payout']
        if date.today().day - date_local.day > 5000 and payout == 5000:
            raise ValidationError()
        return date_local

pythonProject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'show_info.css' %}">
</head>
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">THEBESTCOMPANY</a>

       <form class="d-flex">
        <a href= "{% url 'logout' %}" class="btn btn-danger" type="submit">Выход</a>
      </form>
    </div>
  </div>
</nav>
</header>
<body>
{% block content %}
{% endblock %}
</body>
</html>

pythonProject/templates/bossView.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% extends "base.html" %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'show_info.css' %}">
</head>
<body>
{% block content %}
    <div class="container" >
        <h1 class="display-4 text-dark text-content "align="center">Выберите отдел</h1>
        <div class="mx-auto d-grid gap-2" style="margin-top:20vh; width:300px">
            {% for department in departments %}
                <a href="{% url 'show_department' department.id %}" type="button" class="btn btn btn-outline-primary">{{department.name}}</a>
            {% endfor %}
        </div>
    </div>
{% endblock %}
</body>
</html>

pythonProject/templates/bossViewDepartments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% extends "base.html" %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'show_info.css' %}">
</head>
<body>
{% block content %}
    <div class="container" >
        <h1 class="display-4 text-dark text-content "align="center">Список сотрудников отдела </h1>
        <div class="mx-auto d-grid gap-2" style="margin-top:15vh; width:900px">
             <table class="table">
              <thead class="table-light">
                <tr>
                  <th scope="col">Пользователь</th>
                  <th scope="col">Сотрудник</th>
                  <th scope="col">Контракт</th>
                  <th scope="col">Профиль</th>
                </tr>
              </thead>
            {% for worker in workers %}
                  <tr class="table">
                      <td>{{worker.id_user}}</td>
                      <td>{{worker.first_name}} {{worker.last_name}}</td>
                      <td >{{worker.contract}}</td>
                      <td><a href="{% url 'show_worker' worker.id %}" class="btn btn-outline-success"> Посмотреть</a></td>
                    </tr>
            {% endfor %}

                       </tbody>
    </table>
        </div>
    </div>
{% endblock %}
</body>
</html>

pythonProject/templates/index.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
	{% load static %}
	{% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  <title>Авторизация/Регистрация</title>
	<link rel="stylesheet" href="{% static 'css/style_3.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap" rel="stylesheet">
</head>
	<body>
		<div class="main">
			<input type="checkbox" id="chk" aria-hidden="true">
				<div class="signup">
					<form method="post">
						{% csrf_token %}
						<label for="chk" id="reg" aria-hidden="true">Регистрация</label>
						<input type="text" id="input_username" name="create_user_name" placeholder="User name" required="">
						<input type="email" id="input_email" name="create_email" placeholder="Email" required="">
						<input type="password" name="create_password" placeholder="Password" required="">
						<button id="registr_button" onClick="alert('Заявка отправлена. Ожидайте,скоро Вы получите доступ к своему профилю')">Зарегестрироваться</button>
					</form>
				</div>

				<div class="login">
					<form method="post">
						{% csrf_token %}
						<label for="chk" aria-hidden="true">Авторизация</label>
						<input type="email" name="email" placeholder="Email" required="">
						<input type="password" name="password" placeholder="Password" required="">
						<button>Войти</button>
					</form>
				</div>
		</div>
	{% block javascript %}
		<script src=" https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js">
		</script>
		<script>
			$(document).ready(function(){
				$('#input_email').keyup(function(){
					$.ajax(
						{
							data:$(this).serialize(),
							url: "{% url 'validate_email' %}",
							success:
								function (response){
								if ($('#emailError').length==0)
									$('#input_email').after('<div class="invalid-feedback d-block" id="emailError"></div>');
								if(response.taken == true){
									$('#input_email').removeClass('is-valid').addClass('is-invalid');
									$('#emailError').removeClass('valid-feedback').addClass('invalid-feedback').text("Email существует");
									$('#registr_button').prop('disabled', true);
								} else{
									$('#input_email').removeClass('is-invalid').addClass('is-valid');
									$('#emailError').removeClass('invalid-feedback').addClass('valid-feedback').text("Email доступен");
									$('#registr_button').prop('disabled',false);
								}
								},
							error: function(response){
								console.log(response.responseJSON.errors);
							}
					});
				return false;
				});
			});
		</script>
		<script>
			$(document).ready(function(){
				$('#input_username').keyup(function(){
					$.ajax(
						{
							data:$(this).serialize(),
							url: "{% url 'validate_username' %}",
							success:
								function (response){
								if ($('#usernameError').length==0)
									$('#input_username').after('<div class="invalid-feedback d-block" id="usernameError"></div>');
								if(response.taken == true){
									$('#input_username').removeClass('is-valid').addClass('is-invalid');
									$('#usernameError').removeClass('valid-feedback').addClass('invalid-feedback').text("Имя занято");
									$('#registr_button').prop('disabled', true);
								} else{
									$('#input_username').removeClass('is-invalid').addClass('is-valid');
									$('#usernameError').removeClass('invalid-feedback').addClass('valid-feedback').text("Имя свободно");
									$('#registr_button').prop('disabled',false);
								}
								},
							error: function(response){
								console.log(response.responseJSON.errors);
							}
					});
				return false;
				});
			});
		</script>
	{% endblock javascript %}
	</body>
</html>

pythonProject/templates/notAccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WRONG</title>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Bootstrap 5 404 Error Page</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>


    <body>
        <div class="d-flex align-items-center justify-content-center vh-100">
            <div class="text-center">
                <h1 class="display-1 fw-bold">404</h1>
                <p class="fs-3"> <span class="text-danger">Opps!</span> Page not found.</p>
                <p class="lead">
                    The page you’re looking for doesn’t exist.
                  </p>
                <a href="index.html" class="btn btn-primary">Go Home</a>
            </div>
        </div>
    </body>


</html>

pythonProject/templates/templateForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Начисление зарплаты</title>

</head>
<body>
<script src="https://code.jquery.com/jquery-3.7.1.js"
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous">
</script>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<form method="post" class="mx-auto" style="width: 800px">
    <h1 class="display-4 text-dark text-content "align="center">Начисление зарплаты</h1>
{% csrf_token %}
    <div class="row g-3">
        <div  class="col">
           {{ form.number|as_crispy_field }}
        </div>
         <div class="col">
           {{ form.payout|as_crispy_field }}
        </div>
    </div>
     {{ form.date_salary|as_crispy_field }}
    <button type="submit" id="salary_button" class="btn btn-primary"> Добавить </button>
</form>
{% block javascript %}
		<script src=" https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js">
		</script>
		<script>
			$(document).ready(function(){
				$('#id_number').keyup(function(){
					$.ajax(
						{
							data:$(this).serialize(),
							url: "{% url 'check_numberPay' %}",
							success:
								function (response){
								if ($('#numberError').length==0)
									$('#id_number').after('<div class="invalid-feedback d-block" id="numberError"></div>');
								if(response.taken == true){
									$('#id_number').removeClass('is-valid').addClass('is-invalid');
									$('#numberError').removeClass('valid-feedback').addClass('invalid-feedback').text("Номер существует");
									$('#salary_button').prop('disabled', true);
								} else{
									$('#id_number').removeClass('is-invalid').addClass('is-valid');
									$('#numberError').removeClass('invalid-feedback').addClass('valid-feedback').text("Номер свободен");
									$('#salary_button').prop('disabled',false);
								}
								},
							error: function(response){
								console.log(response.responseJSON.errors);
							}
					});
				return false;
				});
			});
		</script>
{% endblock javascript %}
{% endblock %}
</body>
</html>

pythonProject/templates/workerinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Информация о пользователе</title>
    {% extends "base.html" %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'show_info.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
{% block content %}
<div class="container mt-3">
    <div class="card p-3 text-center">
        <div class="d-flex flex-row justify-content-center mb-3">
            <div class="image">
                <img src=" https://www.gravatar.com/avatar/{{link_img}}?s=120&d=mp " class="rounded-circle">
<span><i class='bx bxs-camera-plus'></i></span> </div>
            <div class="d-flex flex-column ms-3 user-details">
            </div>
        </div>
        <h4> Данные сотрудника</h4>
        <div class="row">
            <div class="col-md-6">
                <div class="name"> <i class="bi bi-card-list"></i> <label>Полное имя сотрудника:</label> <p>{{worker.first_name}} </p> </div>
            </div>
            <div class="col-md-6">
                <div class="inputs"> <i class="bi bi-card-heading"></i> <label>Фамилия сотрудника:</label><p>{{worker.last_name}} </p>  </div>
            </div>
            <div class="col-md-6">
                <div class="inputs"> <i class="bi bi-paperclip"></i> <label>Договор:</label> <p>{{worker.contract}} </p>  </div>
            </div>
            <div class="col-md-6">
                <div class="inputs"> <i class="bi bi-calendar-check-fill"></i> <label>Дата:</label> <p>{{worker.date_work}} <i class="bi bi-check-lg"></i> </p>  </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="about-inputs"> <i class="bi bi-person-workspace"></i> <label>Персональная информация:</label> <textarea class="form-control" type="text" > </textarea> </div>
            </div>
        </div>
        <div class="mt-3 gap-2 d-flex justify-content-end"> <button class="px-3 btn btn-sm btn-outline-primary ">Cancel</button>
            <button  class="px-3 btn btn-sm btn-primary"  onClick="alert('Скоро появится возможность добавления информации о себе!')">Save</button> </div>
    <table class="table">
  <thead>
    <tr>
      <th scope="col">№</th>
      <th scope="col">Руководит</th>
      <th scope="col">Ставка</th>
      <th scope="col">Дата зачисления</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for salar in salary %}
    <tr>
      <th scope="row">{{salar.number}}</th>
      <td>{{salar.boss}}</td>
      <td>{{salar.payout}}</td>
      <td>{{salar.date_salary}}</td>
        <td>
            {% if request == 1 %}
            <a href="{% url 'delete_payout' worker.id_user_id salar.number %}" type="button" class="btn btn-danger">Удалить</a>
            {% endif %}
          </td>


    </tr>
  {% endfor %}
  </tbody>
</table>
    </div>

    <div class="mt-3 gap-2 d-flex justify-content-end">
        {% if request == 1 %}
            <a href="{% url 'create_payout' worker.id_user_id%}" type="button" class="px-3 btn btn-sm btn-primary " >Начислить зарплату</a>
        {% endif %}
    </div>
</div>
{% endblock %}
</body>
</html>